PROMPT='$HEAD$(git_prompt_info)$ARROW'
RPROMPT="%F{#666}%D{%I:%M %p}%f"

HEAD="%F{#f85}󰵮 %1~%f"
ARROW=" %F{yellow}󰁔%f "
ZSH_THEME_GIT_PROMPT_PREFIX=" %F{#444}󱍿%f%F{#999} 󰊤 "
ZSH_THEME_GIT_PROMPT_SUFFIX="%F{#999}%f"
ZSH_THEME_GIT_PROMPT_DIRTY=" %F{#f66}󱓌%f"
ZSH_THEME_GIT_PROMPT_CLEAN=" %F{#5b8}󱓏%f"
